spring:
  thymeleaf:
    cache: false

shiro:
  un-login-html: http://127.0.0.1:9090/loginview
  un-authorized-html: /html/401.html
  un-authorized-json: /auth/unauthorized
  logout-path: /auth/

server:
  port: 9000
